# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Cache .NET packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages  # Путь к папке с кэшем NuGet-пакетов
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}  # Ключ кэша
        restore-keys: |
          nuget-${{ runner.os }}-  # Префикс для восстановления кэша
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
